[[pages]]
path = "Home.py"
name = "ğŸ  Home"

[[pages]]
path = "pages/query.py"
name = "ğŸ§  Assistant Query"
icon = "ğŸ’¬"

[[pages]]
path = "pages/list.py"
name = "ğŸ“„ Indexed Documents"
icon = "ğŸ“"

[[pages]]
path = "pages/indexer.py"
name = "ğŸ“¥ Index New Emails"
icon = "ğŸ—‚ï¸"
